# generate svg github action
on:
  push:
    paths:
      - '.icona/icons.json'

name: Generate SVG files from icons.json

jobs:
  deploy:
    name: Generate SVG files from icons.json
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Generate SVG files
        run: |
          yarn icona generate
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Generate SVG files"
          git push
